---
version: '3.8'
services:
  logstore-init-keyspace:
    container_name: logstore-init-keyspace
    image: cassandra:3.11.5
    init: true
    networks:
      - streamr-network
    command: bash -c "sleep 5 && cqlsh cassandra -f /init_scripts/keyspace.cql && echo keyspace initialized"
    restart: on-failure # exits on success
    volumes:
      - type: bind
        source: ./assets/cassandra
        target: /init_scripts
        read_only: true
        bind:
          propagation: rprivate

  # logstore-arweave:
  #   container_name: logstore-arweave
  #   hostname: logstore-arweave
  #   image: logstore-arweave
  #   build:
  #     context: '.'
  #     dockerfile: ./Dockerfile.arweave
  #   restart: always
  #   ports:
  #     - '1984:1984'
  #   networks:
  #     - streamr-network

  # logstore-kyve:
  #   container_name: logstore-kyve
  #   hostname: logstore-kyve
  #   image: logstore-kyve
  #   build:
  #     context: '.'
  #     dockerfile: ./Dockerfile.kyve
  #   restart: always
  #   networks:
  #     - streamr-network

  logstore-nginx:
    container_name: logstore-nginx
    hostname: logstore-nginx
    image: logstore-nginx
    build:
      context: '.'
      dockerfile: ./Dockerfile.nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '8801:8801'
      - '1317:1317'
      - '26657:26657'
    networks:
      streamr-network:
        aliases:
          - arweave.net
          - sidechain
    # depends_on:
    #   - logstore-arweave
    #   - logstore-kyve

  logstore-base:
    container_name: logstore-base
    image: logstore-base
    build:
      context: ../
      dockerfile: ./dev-network/Dockerfile.base

  logstore-evm-explorer:
    image: appliedblockchain/b-explorer
    container_name: logstore-evm-explorer
    ports:
      - 8802:3000
    environment:
      - ETHEREUM_JSONRPC_ENDPOINT=http://sidechain:8546/
      - CONFIG_FILE_PATH=/home/explorer/app/config.json
    networks:
      - streamr-network
    volumes:
      - ./assets/evm-explorer/config.json:/home/explorer/app/config.json:ro

  logstore-deploy-subgraph:
    container_name: logstore-deploy-subgraph
    image: logstore-deploy-subgraph
    build:
      context: ../
      dockerfile: ./dev-network/Dockerfile.subgraph
    restart: on-failure # exits on success
    networks:
      - streamr-network
    volumes:
      - type: volume
        source: data-logstore-deploy-subgraph
        target: /firstrun
        volume:
          nocopy: false
    depends_on:
      - logstore-base

  logstore-deploy-storage-proxy:
    container_name: logstore-deploy-storage-proxy
    image: logstore-deploy-storage-proxy
    build:
      context: ../
      dockerfile: ./dev-network/Dockerfile.storage-proxy
    restart: on-failure # exits on success
    networks:
      - streamr-network
    volumes:
      - type: volume
        source: data-logstore-deploy-storage-proxy
        target: /firstrun
        volume:
          nocopy: false
      - type: bind
        source: ./assets/storage-proxy/start-in-docker.sh
        target: /usr/local/bin/start-in-docker
    env_file:
      - ./assets/storage-proxy/.env.storage-proxy
    depends_on:
      logstore-base:
        condition: service_completed_successfully

  logstore-broker-1:
    container_name: logstore-broker-1
    hostname: logstore-broker-1
    image: logstore-broker
    command: start-in-docker --join 1000000000000000000000000000000
    build:
      context: ../modules/logstore-node
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '7771:7771'
    networks:
      - streamr-network
    volumes:
      - type: bind
        source: ./assets/broker/docker-1.env.json
        target: /home/node/.logstore/config/default.json
    env_file:
      - ./assets/broker/.env.broker-1
    depends_on:
      logstore-deploy-subgraph:
        condition: service_completed_successfully
      logstore-deploy-storage-proxy:
        condition: service_completed_successfully

  logstore-broker-2:
    container_name: logstore-broker-2
    hostname: logstore-broker-2
    image: logstore-broker
    command: start-in-docker --join 1000000000000000000000000000000
    build:
      context: ../modules/logstore-node
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '7772:7772'
    networks:
      - streamr-network
    volumes:
      - type: bind
        source: ./assets/broker/docker-2.env.json
        target: /home/node/.logstore/config/default.json
    env_file:
      - ./assets/broker/.env.broker-2
    depends_on:
      logstore-deploy-subgraph:
        condition: service_completed_successfully

  logstore-broker-3:
    container_name: logstore-broker-3
    hostname: logstore-broker-3
    image: logstore-broker
    command: start-in-docker --join 1000000000000000000000000000000
    build:
      context: ../modules/logstore-node
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '7773:7773'
    networks:
      - streamr-network
    volumes:
      - type: bind
        source: ./assets/broker/docker-3.env.json
        target: /home/node/.logstore/config/default.json
      - type: bind
        source: ./assets/broker/data/
        target: /home/node/.logstore/data/
    env_file:
      - ./assets/broker/.env.broker-3
    depends_on:
      logstore-deploy-subgraph:
        condition: service_completed_successfully

  # logstore-validator-1:
  #   container_name: logstore-validator-1
  #   hostname: logstore-validator-1
  #   image: logstore-validator
  #   build:
  #     context: ../
  #     dockerfile: ./dev-network/Dockerfile.validator
  #   restart: always
  #   networks:
  #     - streamr-network
  #   volumes:
  #     - type: bind
  #       source: ./assets/validator/start-in-docker.sh
  #       target: /usr/local/bin/start-in-docker
  #   env_file:
  #     - ./assets/validator/.env.validator-1
  #   depends_on:
  #     logstore-base:
  #       condition: service_completed_successfully
  #     logstore-kyve:
  #       condition: service_started
  #     logstore-broker-1:
  #       condition: service_started

  # logstore-validator-2:
  #   container_name: logstore-validator-2
  #   hostname: logstore-validator-2
  #   image: logstore-validator
  #   build:
  #     context: ../
  #     dockerfile: ./dev-network/Dockerfile.validator
  #   restart: always
  #   networks:
  #     - streamr-network
  #   volumes:
  #     - type: bind
  #       source: ./assets/validator/start-in-docker.sh
  #       target: /usr/local/bin/start-in-docker
  #   env_file:
  #     - ./assets/validator/.env.validator-2
  #   depends_on:
  #     logstore-base:
  #       condition: service_completed_successfully
  #     logstore-kyve:
  #       condition: service_started
  #     logstore-broker-2:
  #       condition: service_started

  # logstore-validator-3:
  #   container_name: logstore-validator-3
  #   hostname: logstore-validator-3
  #   image: logstore-validator
  #   build:
  #     context: ../
  #     dockerfile: ./dev-network/Dockerfile.validator
  #   restart: always
  #   networks:
  #     - streamr-network
  #   volumes:
  #     - type: bind
  #       source: ./assets/validator/start-in-docker.sh
  #       target: /usr/local/bin/start-in-docker
  #   env_file:
  #     - ./assets/validator/.env.validator-3
  #   depends_on:
  #     logstore-base:
  #       condition: service_completed_successfully
  #     logstore-kyve:
  #       condition: service_started
  #     logstore-broker-3:
  #       condition: service_started

  # logstore-validator-4:
  #   container_name: logstore-validator-4
  #   hostname: logstore-validator-4
  #   image: logstore-validator
  #   build:
  #     context: ../
  #     dockerfile: ./dev-network/Dockerfile.validator
  #   restart: always
  #   networks:
  #     - streamr-network
  #   volumes:
  #     - type: bind
  #       source: ./assets/validator/start-in-docker.sh
  #       target: /usr/local/bin/start-in-docker
  #   env_file:
  #     - ./assets/validator/.env.validator-4
  #   depends_on:
  #     logstore-base:
  #       condition: service_completed_successfully
  #     logstore-kyve:
  #       condition: service_started
  #     logstore-broker-3:
  #       condition: service_started

  logstore-pulse:
    container_name: logstore-pulse
    hostname: logstore-pulse
    image: logstore-pulse
    build:
      context: ../
      dockerfile: ./dev-network/Dockerfile.pulse
    restart: always
    networks:
      - streamr-network
    env_file:
      - ./assets/pulse/.env.pulse
    volumes:
      - type: bind
        source: ./assets/pulse/start-in-docker.sh
        target: /usr/local/bin/start-in-docker
      - type: volume
        source: data-pulse
        target: /firstrun
    depends_on:
      logstore-base:
        condition: service_completed_successfully
      logstore-deploy-subgraph:
        condition: service_completed_successfully

  # logstore-vector:
  #   container_name: logstore-vector
  #   hostname: logstore-vector
  #   build:
  #     context: ../
  #     dockerfile: ./dev-network/Dockerfile.vector
  #     args:
  #       - NODE_ID=${NODE_ID:?NODE_ID is required}
  #       - INFISICAL_TOKEN=${INFISICAL_TOKEN_VECTOR:?INFISICAL_TOKEN_VECTOR is required}
  #   restart: always
  #   ports:
  #     - '8686:8686'
  #   volumes:
  #     - './assets/vector/vector.toml:/etc/vector/vector.toml'
  #     - '/var/run/docker.sock:/var/run/docker.sock'

networks:
  streamr-network:
    name: streamr-docker-dev_streamr-network
    external: true

volumes:
  cassandra_init_scripts:
  data-pulse:
  data-logstore-deploy-subgraph:
  data-logstore-deploy-storage-proxy:
